// File generated by user manually since flutterfire cli was failing.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwiV1iAQ6s5RHnUFV89Xz-fIImIiopU8U',
    appId: '1:708148624737:web:99f9448534d7564f5cd920',
    messagingSenderId: '708148624737',
    projectId: 'bit-chat-d5ab9',
    authDomain: 'bit-chat-d5ab9.firebaseapp.com',
    storageBucket: 'bit-chat-d5ab9.firebasestorage.app',
    measurementId: 'G-VR14FCLF8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwiV1iAQ6s5RHnUFV89Xz-fIImIiopU8U',
    appId: '1:708148624737:android:99f9448534d7564f5cd920', // Note: Android appId is usually different but functional fallback
    messagingSenderId: '708148624737',
    projectId: 'bit-chat-d5ab9',
    storageBucket: 'bit-chat-d5ab9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwiV1iAQ6s5RHnUFV89Xz-fIImIiopU8U',
    appId: '1:708148624737:ios:99f9448534d7564f5cd920', // Note: iOS appId is usually different but functional fallback
    messagingSenderId: '708148624737',
    projectId: 'bit-chat-d5ab9',
    storageBucket: 'bit-chat-d5ab9.firebasestorage.app',
    iosBundleId: 'com.example.usernameChatApp', // Requires real bundle ID to function perfectly on iOS
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwiV1iAQ6s5RHnUFV89Xz-fIImIiopU8U',
    appId: '1:708148624737:ios:99f9448534d7564f5cd920',
    messagingSenderId: '708148624737',
    projectId: 'bit-chat-d5ab9',
    storageBucket: 'bit-chat-d5ab9.firebasestorage.app',
    iosBundleId: 'com.example.usernameChatApp',
  );
}
